baseURL = "/"
languageCode = "en-us"
theme = "foundation-theme"
title = "aQuiti.ai"
[[menu.main]]
name = "HOME"
url = "#home"
weight = "1"
[[menu.main]]
name = "WHAT WE DO"
url = "#wwd"
weight = "2"
[[menu.main]]
name = "WHY WE DO IT"
url = "#wwdi"
weight = "3"
[[menu.main]]
name = "THE WORLD IN DATA"
url = "#twid"
weight = "4"
[[menu.main]]
name = "ABOUT US"
url = "#about"
weight = "5"
[[menu.main]]
name = "CONTACT US"
url = "#contact"
weight = "6"
[params.about]
aboutTitle = "ABOUT US"
contentOne = "Created by SecDec with the mission to capture, transform, and qualitfy data into machine-readable intelligence that fuels AI and smarter decision-making for next generation financial and risk-based industries."
contentTwo = "aQuiti.ai is an early stage stealth startup."
[params.footer]
addressOne = "300-950 Gladstone - Ottawa, Ontario"
addressTwo = "Ottawa, Ontario"
email = "future@aquiti.ai"
extraInfo = "K1Y 3E6"
footerTitle = "CONTACT US"
privacyPolicy = "Privacy policy"
[params.header]
discription1 = "Small data can have a big impact."
discription2 = "We apply chaos theory to data science by curating precision data feeds tailored to next generation finance and risk-based industries."
title1 = "aQuiti"
title2 = "ai"
[params.main]
contentOneBody = "A simple and easy to use hugo theme that anyone can expand and develop further. The design was ported to a Hugo Theme from the youtube video series posted by Gary Jennings. You can easily change the layout of this section in the main.html partial in the themes dir"
contentOneTitle = "Easy to use"
contentTwoBody = "You can see Gary's tutorial [here:](https://www.youtube.com/watch?v=2QcpR6cHpnk) *Markdown* can be used in these two panels to quickly **style** content."
contentTwoTitle = "See Gary's Tutorial"
[params.twid]
contentOne1 = "Global data will grow "
contentOne2 = "2X"
contentOne3 = "between 2022 to 2025 to 181 Zetabytes"
contentThree1 = "AI markets revenues will rise"
contentThree2 = "2X"
contentThree3 = "by 2024 to $560 billion"
contentTwo1 = "AI software markets will grow"
contentTwo2 = "4X"
contentTwo3 = "by 2025 to $120 billion"
twidTitle = "THE WORLD IN DATA"
[params.wwd]
content = "Aquiti is where chaos theory meets data science. We seek the Butterfly Effect - data that is accurate, timely and highly consequential."
row11Content = "We discover unique and rare data"
row11Number = "1"
row11Title = "Find"
row12Content = "We collect and curate data sources"
row12Number = "2"
row12Title = "Mine"
row21Content = "We enrich data to high standards of accuracy"
row21Number = "3"
row21Title = "Refine"
row22Content = "We tailor data feeds to our customers exacting needs"
row22Number = "4"
row22Title = "Deliver"
wwdTitle = "WHAT WE DO"
[params.wwdi]
contentOne = "Financial marker and risk-based industries need highly accurate data to make timely decisions. Data services are plentiful but the accuracy of their data is not."
contentTwo1 = "In a complex, interconnected and global economy, speed and accurary are vital."
contentTwo2 = "Small changes can lead to big consequences. Trusting your data is critical. Even the smartest system make mistakes if the data and models driving them are flawed and biased."
contentTwo3 = "Next generation AI needs exceptionally accurate data to drive faster-than-real-time decision-making."
wwdiTitle = "WHY WE DO IT"
